#!/bin/sh

git config --global --add safe.directory /odoo/sidilcode13/*

# Restoring GIT working copies:
git -C /odoo/sidilcode13/SIDIL-Installer/ checkout .
git -C /odoo/sidilcode13/SIDIL-Installer/ checkout sidil_installer
# Creating generic code dir:
cp -av /odoo/sidilcode13/SIDIL-Installer/ /odoo/sidilcode13/SIDIL-Odoo/
git -C /odoo/sidilcode13/SIDIL-Odoo/ checkout main

echo "Creating and setting-up 'odoo' user and group if they do not exist . . ."
id -u odoo || useradd odoo
usermod -d /odoo odoo

# Reseting /odoo tree permissions:
echo "(1/7) Setgid folders under /odoo . . ."
find /odoo/ -type d -exec chmod g+s {} \;

echo "(2/7) Folder user and group writes to /odoo . . ."
bash -c "chmod ug+rwX,o-wx,o+rX /odoo/"

echo "(3/7) User and Group writes to subfolders of /odoo/releases . . ."
bash -c "chmod ug+rwX,o-wx,o+rX -R /odoo/releases"

echo "(4/7) User and Group writes to subfolders of /odoo/sidilcode13 . . ."
bash -c "chmod ug+rwX,o-wx,o+rX -R /odoo/sidilcode13/"

echo "(5/7) User and Group writes to subfolders of /odoo/VirtualEnvs . . ."
bash -c "chmod ug+rwX,o-wx,o+rX -R /odoo/VirtualEnvs/"

echo "(6/7) Only User writes to subfolders of /odoo/configs, /odoo/logs and /odoo/stages . . ."
bash -c "chmod u+rwX,g+rX,g-w,o-wx,o+rX -R /odoo/{configs,logs,stages}"

echo "(7/7) Give /odoo tree to user odoo . . ."
chown odoo:odoo -R /odoo/

